version: '3.8'

services:
  # Redis 서비스 설정
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data                 # 데이터 지속성을 위한 볼륨 설정
    networks:
      - app-network

  # 애플리케이션 서비스 설정
  antifragile:
    image: ${DOCKER_USERNAME}/antifragile-dev:latest
    container_name: antifragile-dev
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=develop   # Spring 프로파일 설정
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local